### ISSUE TITLE
utteranc.es comments don't work

### ISSUE THREAD

**Issue by dlukes** [rednafi/digressions#5]
Tried to leave a comment on the [pathlib post](https://rednafi.github.io/digressions/python/2020/04/13/python-pathlib.html) but got an error:

> Error: utterances is not installed on rednafi/digressions. If you own this repo, [install the app](https://github.com/apps/utterances). Read more about this change in [the PR](https://github.com/utterance/utterances/pull/25).

Leaving the comment here instead to remind myself to post it if the comment section gets fixed:

> Great writeup! Any thoughts on what's missing from the `pathlib` API and still makes you reach for those older libraries? In my experience, I often end up resorting to `shutil.rmtree`, but there are probably other convenience functions like this :)

**Comment by rednafi** [comment]
Thank you for pointing out the utterance issue. I still often use `os` module instead of `pathlib` for performance issues. Pathlib is considerably slower than os modules, which becomes apparent while doing path manipulation on a very large number of files.

**Comment by rednafi** [comment]
Utterance comment is working now!
